// This file was autogenerated by ./build/depswriter.py.
// Please do not edit.
goog.addDependency('../src/base.js', ['goog'], []);
goog.addDependency('../src/controllers/color_ramp_controller.js', ['ColorRampController'], ['PanelManager', 'ServiceLayer']);
goog.addDependency('../src/controllers/filter_controller.js', ['FilterController'], ['ColorRampController', 'FilterView', 'TimeStepController']);
goog.addDependency('../src/controllers/panel_manager.js', ['PanelManager'], ['MDSPanel', 'MapPanel', 'TimePanel', 'selectionManager']);
goog.addDependency('../src/controllers/selection_manager.js', ['selectionManager'], []);
goog.addDependency('../src/controllers/selector.js', ['SVGSelection'], []);
goog.addDependency('../src/controllers/time_step_controller.js', ['TimeStepController'], ['PanelManager', 'ServiceLayer', 'TimeStepFilterView']);
goog.addDependency('../src/dash.js', ['dash'], ['FilterController', 'PanelManager', 'ServiceLayer']);
goog.addDependency('../src/models/color_map.js', ['ColorMap'], []);
goog.addDependency('../src/models/service_layer.js', ['ServiceLayer'], []);
goog.addDependency('../src/views/filter_view.js', ['FilterView'], ['ColorRampController', 'TimeStepController']);
goog.addDependency('../src/views/map_panel.js', ['MapPanel'], ['ColorMap', 'Panel', 'ServiceLayer', 'selectionManager']);
goog.addDependency('../src/views/mds_panel.js', ['MDSPanel'], ['Panel']);
goog.addDependency('../src/views/panel.js', ['Panel'], ['ServiceLayer', 'selectionManager']);
goog.addDependency('../src/views/popup.js', ['Popup'], []);
goog.addDependency('../src/views/time_panel.js', ['TimePanel'], ['Panel', 'Popup', 'SVGSelection', 'ServiceLayer', 'selectionManager']);
goog.addDependency('../src/views/time_step_filter_view.js', ['TimeStepFilterView'], []);
